insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (46, 3, 'Paraguayan Windmill Grass', 3, '2025-06-07', 44);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (75, 20, 'Bracted Lousewort', 4, '2024-09-23', 18);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (48, 12, 'Julella Lichen', 3, '2025-04-01', 39);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (12, 6, 'Trichocereus', 4, '2025-05-03', 21);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (25, 7, 'Turk''s Head', 1, '2025-02-28', 42);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (52, 2, 'Mariposa Phacelia', 4, '2025-07-04', 78);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (80, 1, 'Santa Catalina Island Bedstraw', 1, '2025-03-27', 54);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (53, 9, 'Giant Airplant', 2, '2025-07-08', 48);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (1, 20, 'Basin Nemophila', 2, '2025-06-02', 62);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (54, 10, 'Landolphia Rubber', 1, '2024-11-20', 10);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (80, 20, 'Parmotrema Lichen', 4, '2025-01-23', 73);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (48, 12, 'Blue Mountain Biscuitroot', 3, '2025-03-16', 19);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (26, 16, 'Trailing Windmills', 4, '2025-05-28', 80);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (66, 2, 'Munnik Fescue', 3, '2025-01-20', 37);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (33, 14, 'Wright''s Stonecrop', 1, '2024-12-07', 84);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (36, 6, 'Pillwort', 3, '2025-05-31', 36);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (28, 7, 'Syrian Juniper', 2, '2025-02-04', 29);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (40, 13, 'California Fishscale Lichen', 2, '2024-12-17', 84);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (42, 8, 'Spreading Fissurewort', 1, '2024-12-23', 55);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (51, 11, 'Violet Draperia', 4, '2025-07-08', 77);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (6, 16, 'Ceanothus', 2, '2024-09-16', 68);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (60, 20, 'Puerto Rico Ghostplant', 2, '2024-12-03', 32);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (12, 7, 'Caribbean Pine', 2, '2024-09-05', 37);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (66, 9, 'Hayfield Tarweed', 2, '2025-04-18', 90);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (54, 17, 'Cracked Lichen', 3, '2025-07-26', 51);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (55, 13, 'South American Rubberweed', 3, '2025-02-20', 88);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (69, 4, 'Greygreen Reindeer Lichen', 4, '2025-03-29', 33);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (2, 11, 'Rhagadiolus', 2, '2025-04-14', 34);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (24, 15, 'Longleaf Starwort', 3, '2025-04-06', 76);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (72, 18, 'Pugnacious Blackberry', 1, '2025-06-07', 90);
