insert into userr (first_name, last_name, username, password, role, is_active) values ('Aaren', 'Neal', 'Aaren.Neal', '6w995f1859', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Brit', 'Francis', 'Brit.Francis', '5G77tFH329', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Hester', 'Maillard', 'Hester.Maillard', 'Va47rKo102', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Randolf', 'Eilhart', 'Randolf.Eilhart', 'tF48N8D224', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Demetrius', 'Dallan', 'Demetrius.Dallan', 'M490co3941', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Esra', 'Necrews', 'Esra.Necrews', 'iK71bnz582','TRAINEE',  true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Lexine', 'Baumford', 'Lexine.Baumford', 'WL14Wr1586', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Roseanna', 'Bourhill', 'Roseanna.Bourhill', 'xq72p1Z142', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Meredithe', 'Mustill', 'Meredithe.Mustill', 'fk58zqI413', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Adan', 'Petris', 'Adan.Petris', 'sT61mfp230', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Tiffanie', 'Yokley', 'Tiffanie.Yokley', 'jj99ZIO572', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Justus', 'Sabberton', 'Justus.Sabberton', '5S98eO5738', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Auberta', 'Elflain', 'Auberta.Elflain', 'RY87Nlj678', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Reiko', 'Busher', 'Reiko.Busher', 'SU663qe006', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Dode', 'Mithan', 'Dode.Mithan', '6M95iut618', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Min', 'Rosenblad', 'Min.Rosenblad', 'iP012yc808', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Edgard', 'Prinne', 'Edgard.Prinne', 'oR35QNV778', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Marlane', 'Antonsson', 'Marlane.Antonsson', 'V376irw626', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Malachi', 'Wellum', 'Malachi.Wellum', 'zg44X4D195', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Shirleen', 'Bysouth', 'Shirleen.Bysouth', 'tn23LNn096', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Trenton', 'Meltetal', 'Trenton.Meltetal', 'tP576Ke619', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Peadar', 'Hillan', 'Peadar.Hillan', 'rv22E0d175', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Garik', 'Skillicorn', 'Garik.Skillicorn', 'vf04wB8564', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Giraldo', 'Castellan', 'Giraldo.Castellan', 'SO512md929', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Link', 'Brewin', 'Link.Brewin', 'N111IKj058', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cammi', 'Road', 'Cammi.Road', 'BE85hs7382', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Allen', 'Butteris', 'Allen.Butteris', 'UY73Iz3858', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Kenton', 'MacDearmid', 'Kenton.MacDearmid', 'oI20L1j800', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Dominique', 'Penkman', 'Dominique.Penkman', 'F7078U5915', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Fayre', 'McCooke', 'Fayre.McCooke', 'Ep99sLc230', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Maude', 'Habgood', 'Maude.Habgood', 'VQ50mtc440', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Minny', 'Caldeiro', 'Minny.Caldeiro', '9w13KXZ838', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Levey', 'Pearn', 'Levey.Pearn', 'zA46Mxl615', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Kellby', 'Breddy', 'Kellby.Breddy', 'Tb34nHO702', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Fanny', 'Gillam', 'Fanny.Gillam', 'aw91Akj059', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Collin', 'Blaxton', 'Collin.Blaxton', 'zx563Ca398', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Vida', 'Lygo', 'Vida.Lygo', 'mj41CwZ972', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Claretta', 'Tytterton', 'Claretta.Tytterton', 'pj843N4250', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Wake', 'Petrozzi', 'Wake.Petrozzi', 'TW64O3J932', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Aime', 'Dunnett', 'Aime.Dunnett', 'KY28PyT977', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Shepard', 'Wikey', 'Shepard.Wikey', 'On42Rzj331', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Prescott', 'Strutt', 'Prescott.Strutt', 'cI45Ajg488', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Veronike', 'Iffe', 'Veronike.Iffe', 'Qo69R7v752', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Jamal', 'Lieber', 'Jamal.Lieber', 'WE27d9I912', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Avictor', 'Murgatroyd', 'Avictor.Murgatroyd', 'Fs56YVV382', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Sterne', 'Lembrick', 'Sterne.Lembrick', 'sj69BHS873', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Panchito', 'Scutchin', 'Panchito.Scutchin', 'GY95qvK088', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cilka', 'Wodham', 'Cilka.Wodham', 'J227UZU753', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Blondy', 'Pash', 'Blondy.Pash', 'DC96iRo049', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cyrus', 'Berndtssen', 'Cyrus.Berndtssen', 'Mr802ho566', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Brittany', 'Bartoleyn', 'Brittany.Bartoleyn', 'rU42la4273', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Bentlee', 'Rewcastle', 'Bentlee.Rewcastle', 'hy02lVO474', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Morly', 'McPhaden', 'Morly.McPhaden', '5J209uv844', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Missy', 'Senechault', 'Missy.Senechault', 'EE98RFl807', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Rene', 'Marshalleck', 'Rene.Marshalleck', '0629OZm932', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Flore', 'Fullerd', 'Flore.Fullerd', 'BF959Hi701', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Nico', 'Sorton', 'Nico.Sorton', 'rA58WFa238', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Kristina', 'Vaugham', 'Kristina.Vaugham', 'O344XWz005', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Melodie', 'Forlonge', 'Melodie.Forlonge', '2q81mbQ066', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cari', 'Cellone', 'Cari.Cellone', 'Ir89ZuE507', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cherlyn', 'Bramley', 'Cherlyn.Bramley', 'x098DWE840', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Maggy', 'Wallis', 'Maggy.Wallis', 'mO85ED5492', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Raul', 'Sybry', 'Raul.Sybry', 'zz41UGU638', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Yasmeen', 'Duddle', 'Yasmeen.Duddle', 'mj37u2r793', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Ezequiel', 'Kimmince', 'Ezequiel.Kimmince', 'Cx910EL870', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Wyndham', 'Gingles', 'Wyndham.Gingles', 'Fp79tb7285', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Haskel', 'Brocking', 'Haskel.Brocking', 'Rd14F9D047', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Elvin', 'Garken', 'Elvin.Garken', 'Xr39BO9348', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Lanita', 'Dinnington', 'Lanita.Dinnington', '9S61Ise046', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Alfy', 'Yendall', 'Alfy.Yendall', '8X81Gca808', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Tamas', 'Bowyer', 'Tamas.Bowyer', 'To40X9B162', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Imojean', 'Kienlein', 'Imojean.Kienlein', '7q52irM810', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Francene', 'Darville', 'Francene.Darville', 'ya85N7c376', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Pennie', 'Thomke', 'Pennie.Thomke', 'jO26259681', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Trula', 'Brantzen', 'Trula.Brantzen', 'mu04Arg782', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Derrek', 'Wilbor', 'Derrek.Wilbor', 'Y530H1o284', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Findley', 'Loutheane', 'Findley.Loutheane', '9q986fz774', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Elihu', 'Bresman', 'Elihu.Bresman', 'eJ91Nc2152', 'TRAINEE', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Addison', 'Machen', 'Addison.Machen', 'x465qBZ953', 'TRAINEE', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Hermione', 'Matei', 'Hermione.Matei', 'FW91iyf004', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Miguela', 'Andres', 'Miguela.Andres', 'YY086xU351', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Georgette', 'Kinnard', 'Georgette.Kinnard', 'xn58UUu609', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Wolfy', 'Blackater', 'Wolfy.Blackater', 'SS84GPk586', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Dorella', 'Janicijevic', 'Dorella.Janicijevic', 'h986QUj305', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Nerte', 'Aronovich', 'Nerte.Aronovich', 'Kr580q6754', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cilka', 'Gehrts', 'Cilka.Gehrts', '5M84VQa307', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Ingra', 'McCurlye', 'Ingra.McCurlye', 'Hs66do6357', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Dara', 'Meaney', 'Dara.Meaney', 'Is98Sd1620', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Jude', 'Spinley', 'Jude.Spinley', '5M40oid852', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Ingrid', 'Colcomb', 'Ingrid.Colcomb', 'WC77lC0812', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Cornie', 'Hofer', 'Cornie.Hofer', 'UF53Sgn763', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Chryste', 'Duffell', 'Chryste.Duffell', 'vP23tiE183', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Karlyn', 'Heatley', 'Karlyn.Heatley', 'kB12JfX823', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Jonathan', 'Eddowes', 'Jonathan.Eddowes', 'dc29LDW216', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Aimee', 'Zmitrovich', 'Aimee.Zmitrovich', 'M3640xt739', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Erroll', 'Oldman', 'Erroll.Oldman', 'er89yAf657', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Horatia', 'Dilrew', 'Horatia.Dilrew', 'eo15RJZ438', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Lyda', 'Saffill', 'Lyda.Saffill', '3T27IvQ833', 'TRAINER', false);
insert into userr (first_name, last_name, username, password, role, is_active) values ('Merrel', 'Proby', 'Merrel.Proby', 'du74Ml2494', 'TRAINER', true);
insert into userr (first_name, last_name, username, password, role, is_active) values ('admin', 'admin', 'admin.admin', 'admin', 'ADMIN', true);



insert into training_type (training_type_name) values ('RESISTANCE');
insert into training_type (training_type_name) values ('STRETCHING');
insert into training_type (training_type_name) values ('YOGA');
insert into training_type (training_type_name) values ('ZUMBA');
insert into training_type (training_type_name) values ('UNKNOWN');



insert into trainee (date_of_birth, address, user_id) values ('2003-04-18', 'Room 211', 1);
insert into trainee (date_of_birth, address, user_id) values ('2009-11-13', 'Suite 6', 2);
insert into trainee (date_of_birth, address, user_id) values ('2000-07-31', 'Room 1725', 3);
insert into trainee (date_of_birth, address, user_id) values ('2004-10-24', 'Suite 8', 4);
insert into trainee (date_of_birth, address, user_id) values ('2009-02-21', 'Suite 75', 5);
insert into trainee (date_of_birth, address, user_id) values ('2000-08-01', '10th Floor', 6);
insert into trainee (date_of_birth, address, user_id) values ('2001-01-30', 'Suite 86', 7);
insert into trainee (date_of_birth, address, user_id) values ('2002-11-02', 'Apt 1678', 8);
insert into trainee (date_of_birth, address, user_id) values ('2007-08-22', 'Room 18', 9);
insert into trainee (date_of_birth, address, user_id) values ('2004-02-13', 'Apt 405', 10);
insert into trainee (date_of_birth, address, user_id) values ('2003-07-01', 'PO Box 63606', 11);
insert into trainee (date_of_birth, address, user_id) values ('2005-08-04', 'PO Box 60074', 12);
insert into trainee (date_of_birth, address, user_id) values ('2001-12-05', 'Room 69', 13);
insert into trainee (date_of_birth, address, user_id) values ('2001-09-04', 'Apt 327', 14);
insert into trainee (date_of_birth, address, user_id) values ('2007-11-28', '3rd Floor', 15);
insert into trainee (date_of_birth, address, user_id) values ('2005-05-22', 'PO Box 83868', 16);
insert into trainee (date_of_birth, address, user_id) values ('2005-01-13', 'Suite 11', 17);
insert into trainee (date_of_birth, address, user_id) values ('2010-05-14', 'Suite 81', 18);
insert into trainee (date_of_birth, address, user_id) values ('2005-10-09', 'PO Box 50503', 19);
insert into trainee (date_of_birth, address, user_id) values ('2005-04-11', 'PO Box 54584', 20);
insert into trainee (date_of_birth, address, user_id) values ('2003-01-22', 'PO Box 96633', 21);
insert into trainee (date_of_birth, address, user_id) values ('2010-06-15', 'Suite 88', 22);
insert into trainee (date_of_birth, address, user_id) values ('2008-01-15', 'Apt 838', 23);
insert into trainee (date_of_birth, address, user_id) values ('2002-09-30', '18th Floor', 24);
insert into trainee (date_of_birth, address, user_id) values ('2008-09-06', '17th Floor', 25);
insert into trainee (date_of_birth, address, user_id) values ('2008-12-10', 'PO Box 26938', 26);
insert into trainee (date_of_birth, address, user_id) values ('2004-11-03', 'PO Box 73021', 27);
insert into trainee (date_of_birth, address, user_id) values ('2003-12-31', '3rd Floor', 28);
insert into trainee (date_of_birth, address, user_id) values ('2003-05-21', 'Suite 91', 29);
insert into trainee (date_of_birth, address, user_id) values ('2001-11-12', 'Apt 95', 30);
insert into trainee (date_of_birth, address, user_id) values ('2008-09-05', '17th Floor', 31);
insert into trainee (date_of_birth, address, user_id) values ('2002-04-13', 'Room 1971', 32);
insert into trainee (date_of_birth, address, user_id) values ('2005-02-07', 'Apt 162', 33);
insert into trainee (date_of_birth, address, user_id) values ('2009-12-21', 'Room 523', 34);
insert into trainee (date_of_birth, address, user_id) values ('2005-08-14', 'Apt 338', 35);
insert into trainee (date_of_birth, address, user_id) values ('2000-12-13', 'Room 1959', 36);
insert into trainee (date_of_birth, address, user_id) values ('2000-11-24', 'PO Box 62659', 37);
insert into trainee (date_of_birth, address, user_id) values ('2007-08-11', 'Suite 68', 38);
insert into trainee (date_of_birth, address, user_id) values ('2003-08-05', '6th Floor', 39);
insert into trainee (date_of_birth, address, user_id) values ('2005-07-26', 'Room 1304', 40);
insert into trainee (date_of_birth, address, user_id) values ('2000-09-28', 'Suite 19', 41);
insert into trainee (date_of_birth, address, user_id) values ('2004-05-02', 'Suite 95', 42);
insert into trainee (date_of_birth, address, user_id) values ('2007-05-07', 'Suite 43', 43);
insert into trainee (date_of_birth, address, user_id) values ('2008-02-28', 'PO Box 79330', 44);
insert into trainee (date_of_birth, address, user_id) values ('2008-07-14', '13th Floor', 45);
insert into trainee (date_of_birth, address, user_id) values ('2003-01-04', 'Apt 1224', 46);
insert into trainee (date_of_birth, address, user_id) values ('2006-12-01', '6th Floor', 47);
insert into trainee (date_of_birth, address, user_id) values ('2007-10-09', 'Suite 78', 48);
insert into trainee (date_of_birth, address, user_id) values ('2010-04-22', 'Room 360', 49);
insert into trainee (date_of_birth, address, user_id) values ('2002-03-02', 'Room 935', 50);
insert into trainee (date_of_birth, address, user_id) values ('2004-12-14', 'Suite 42', 51);
insert into trainee (date_of_birth, address, user_id) values ('2002-11-17', '2nd Floor', 52);
insert into trainee (date_of_birth, address, user_id) values ('2004-09-08', 'Apt 1939', 53);
insert into trainee (date_of_birth, address, user_id) values ('2002-04-26', 'Room 850', 54);
insert into trainee (date_of_birth, address, user_id) values ('2004-07-07', 'Apt 785', 55);
insert into trainee (date_of_birth, address, user_id) values ('2006-09-02', 'Suite 17', 56);
insert into trainee (date_of_birth, address, user_id) values ('2006-08-05', '8th Floor', 57);
insert into trainee (date_of_birth, address, user_id) values ('2008-06-21', 'Suite 63', 58);
insert into trainee (date_of_birth, address, user_id) values ('2005-02-24', 'Room 1017', 59);
insert into trainee (date_of_birth, address, user_id) values ('2004-01-24', 'Apt 917', 60);
insert into trainee (date_of_birth, address, user_id) values ('2006-06-06', 'Room 984', 61);
insert into trainee (date_of_birth, address, user_id) values ('2009-08-23', 'Apt 1495', 62);
insert into trainee (date_of_birth, address, user_id) values ('2010-06-24', 'Apt 1923', 63);
insert into trainee (date_of_birth, address, user_id) values ('2009-07-28', 'Suite 59', 64);
insert into trainee (date_of_birth, address, user_id) values ('2006-12-24', 'Apt 303', 65);
insert into trainee (date_of_birth, address, user_id) values ('2010-07-16', 'Suite 4', 66);
insert into trainee (date_of_birth, address, user_id) values ('2002-12-14', 'Suite 67', 67);
insert into trainee (date_of_birth, address, user_id) values ('2000-11-23', 'Room 698', 68);
insert into trainee (date_of_birth, address, user_id) values ('2006-03-28', 'Room 1861', 69);
insert into trainee (date_of_birth, address, user_id) values ('2001-06-08', 'Room 1166', 70);
insert into trainee (date_of_birth, address, user_id) values ('2004-08-04', 'PO Box 10224', 71);
insert into trainee (date_of_birth, address, user_id) values ('2002-01-06', 'Room 1444', 72);
insert into trainee (date_of_birth, address, user_id) values ('2008-09-12', 'PO Box 87510', 73);
insert into trainee (date_of_birth, address, user_id) values ('2006-04-25', 'Room 1500', 74);
insert into trainee (date_of_birth, address, user_id) values ('2009-05-22', 'Room 136', 75);
insert into trainee (date_of_birth, address, user_id) values ('2002-03-14', 'Apt 1811', 76);
insert into trainee (date_of_birth, address, user_id) values ('2005-07-08', 'PO Box 59622', 77);
insert into trainee (date_of_birth, address, user_id) values ('2005-01-29', 'Suite 5', 78);
insert into trainee (date_of_birth, address, user_id) values ('2010-05-19', 'Suite 78', 79);
insert into trainee (date_of_birth, address, user_id) values ('2003-09-13', '4th Floor', 80);



insert into trainer (specialization, user_id) values (4, 81);
insert into trainer (specialization, user_id) values (3, 82);
insert into trainer (specialization, user_id) values (4, 83);
insert into trainer (specialization, user_id) values (2, 84);
insert into trainer (specialization, user_id) values (2, 85);
insert into trainer (specialization, user_id) values (2, 86);
insert into trainer (specialization, user_id) values (1, 87);
insert into trainer (specialization, user_id) values (2, 88);
insert into trainer (specialization, user_id) values (2, 89);
insert into trainer (specialization, user_id) values (2, 90);
insert into trainer (specialization, user_id) values (3, 91);
insert into trainer (specialization, user_id) values (2, 92);
insert into trainer (specialization, user_id) values (3, 93);
insert into trainer (specialization, user_id) values (2, 94);
insert into trainer (specialization, user_id) values (3, 95);
insert into trainer (specialization, user_id) values (2, 96);
insert into trainer (specialization, user_id) values (3, 97);
insert into trainer (specialization, user_id) values (2, 98);
insert into trainer (specialization, user_id) values (3, 99);
insert into trainer (specialization, user_id) values (4, 100);


insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (78, 11, 'Crookedstem Aster', 1, '2024-12-18', 38);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (78, 7, 'Galearis', 3, '2025-03-08', 38);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (78, 17, 'Calammophila', 1, '2025-03-30', 80);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (78, 6, 'Arizona Cinquefoil', 1, '2025-01-20', 51);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (78, 16, 'Fishtail Swordfern', 4, '2025-07-28', 61);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (39, 10, 'Roadside Toadflax', 1, '2025-05-10', 40);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (37, 10, 'Cartilage Lichen', 3, '2025-07-13', 89);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (3, 10, 'Canadian Wildrye', 4, '2025-07-06', 28);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (35, 10, 'Tall Buckwheat', 1, '2025-06-03', 34);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (62, 10, 'Cojoba', 2, '2024-09-17', 12);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (57, 4, 'Yellow Evening Primrose', 3, '2024-08-31', 68);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (64, 1, 'Annual Mercury', 1, '2025-07-28', 60);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (29, 17, 'Small-leaf Angelica', 3, '2024-09-15', 39);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (52, 2, 'Brome-like Sedge', 2, '2025-04-20', 58);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (66, 6, 'Coastal Live Oak', 2, '2025-06-10', 79);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (69, 17, 'Pterocarpus', 1, '2024-12-19', 25);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (55, 11, 'Eaton''s Fleabane', 3, '2025-01-08', 63);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (4, 13, 'Chapman''s Butterwort', 4, '2024-08-23', 82);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (63, 11, 'Arctic Kidney Lichen', 1, '2024-12-24', 65);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (15, 4, 'Western Pansy', 2, '2025-03-05', 27);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (54, 4, 'Koolau Range Labordia', 4, '2024-12-27', 51);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (21, 7, 'Flatspine Stickseed', 4, '2025-05-30', 53);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (34, 9, 'Cultivated Tobacco', 1, '2024-10-19', 27);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (9, 2, 'Mountain Lichen', 3, '2025-04-29', 15);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (9, 19, 'Golden Spiderflower', 1, '2024-08-29', 64);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (70, 18, 'Italian Woodbine', 2, '2025-05-23', 50);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (7, 9, 'Pearlbrush', 3, '2025-01-01', 33);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (51, 3, 'Dot Lichen', 4, '2024-08-19', 30);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (45, 5, 'Mosquito Bills', 1, '2024-10-02', 53);
insert into training (trainee_id, trainer_id, training_name , training_type_id, training_date, duration ) values (44, 4, 'Sedge', 4, '2024-08-26', 79);

insert into trainer_trainee (trainee_id, trainer_id) values (78, 11);
insert into trainer_trainee (trainee_id, trainer_id) values (78, 7);
insert into trainer_trainee (trainee_id, trainer_id) values (78, 17);
insert into trainer_trainee (trainee_id, trainer_id) values (78, 6);
insert into trainer_trainee (trainee_id, trainer_id) values (78, 16);
insert into trainer_trainee (trainee_id, trainer_id) values (39, 10);
insert into trainer_trainee (trainee_id, trainer_id) values (37, 10);
insert into trainer_trainee (trainee_id, trainer_id) values (3, 10);
insert into trainer_trainee (trainee_id, trainer_id) values (35, 10);
insert into trainer_trainee (trainee_id, trainer_id) values (62, 10);
insert into trainer_trainee (trainee_id, trainer_id) values (57, 4);
insert into trainer_trainee (trainee_id, trainer_id) values (64, 1);
insert into trainer_trainee (trainee_id, trainer_id) values (29, 17);
insert into trainer_trainee (trainee_id, trainer_id) values (52, 2);
insert into trainer_trainee (trainee_id, trainer_id) values (66, 6);
insert into trainer_trainee (trainee_id, trainer_id) values (69, 17);
insert into trainer_trainee (trainee_id, trainer_id) values (55, 11);
insert into trainer_trainee (trainee_id, trainer_id) values (4, 13);
insert into trainer_trainee (trainee_id, trainer_id) values (63, 11);
insert into trainer_trainee (trainee_id, trainer_id) values (15, 4);
insert into trainer_trainee (trainee_id, trainer_id) values (54, 4);
insert into trainer_trainee (trainee_id, trainer_id) values (21, 7);
insert into trainer_trainee (trainee_id, trainer_id) values (34, 9);
insert into trainer_trainee (trainee_id, trainer_id) values (9, 2);
insert into trainer_trainee (trainee_id, trainer_id) values (9, 19);
insert into trainer_trainee (trainee_id, trainer_id) values (70, 18);
insert into trainer_trainee (trainee_id, trainer_id) values (7, 9);
insert into trainer_trainee (trainee_id, trainer_id) values (51, 3);
insert into trainer_trainee (trainee_id, trainer_id) values (45, 5);
insert into trainer_trainee (trainee_id, trainer_id) values (44, 4);